In [2]:

import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

#scores:ndarray | None = None # 學生的分數
#scores_df:DataFrame | None = None # 學生分數的DataFrame

scores:ndarray = np.random.randint(40, 101, size=(50, 5))
scores_df:DataFrame = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df.groupby("性別")[['國文', '英文', '數學', '地理', '歷史']].agg('mean')

       國文     英文     數學     地理     歷史
性別
女   64.64  74.68  70.76  69.36  73.48
男   72.48  66.92  70.16  70.04  66.68

In [3]:
scores_df['總分'] = scores_df[['國文', '英文', '數學', '地理', '歷史']].sum(axis=1)

scores_df['總分階級'] = pd.cut(
    scores_df['總分'],
    bins=[0, 250, 350, 500],
    labels=['低分區', '一般區', '高分區']
)

scores_df.groupby(['性別', '總分階級'])['總分'].agg(['count', 'mean', 'min', 'max'])

         count        mean  min  max
性別 總分階級
女  一般區      12  308.833333  262  344
   高分區      13  393.615385  357  452
男  一般區      14  318.857143  260  350
   高分區      11  381.181818  358  411